param (
  [string]$inputFile,
  [string]$outputFile
)

Write-Host "`nReading $inputFile and will extract result to $outputFile"

# Some regex sample
#$email_regex = ‘\b[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\b’
#$ip_regex = ‘\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b’
#$url_regex = ‘([a-zA-Z]{3,})://([\w-]+\.)+[\w-]+(/[\w- ./?%&=]*)*?’

#extract image from X-Plane WED file that are autogenerated by WED O Maker.  
#look for string with .jpg extension

$regex = "[0-9]+.jpg"
select-string -Path $inputFile -Pattern $regex -AllMatches | % { $_.Matches } | % { $_.Value } | Sort | Get-Unique > $outputFile


#Write-Host "`nExit the script"
